### ISSUE TITLE
[Request] - Add GitHub Actions CI for Build

### ISSUE THREAD

**Issue by PatilShreyas** [MindorksOpenSource/ridesharing-uber-lyft-app#2]
Hi @amitshekhariitbhu,
It would be nice to have a CI support for this repository which will be triggered on every Push/Pull Request. Also, new usable ***APK*** will be generated every time which will help you to review Pull requests too.
I've forked this repository and integrated GitHub Actions CI. If it looks good to you, I'm happy to open PR. 

**Files need to change:**
- [`app/build.gradle`](https://github.com/PatilShreyas/ridesharing-uber-lyft-app/blob/master/app/build.gradle)
- [`.github/workflows/Build.yml`](https://github.com/PatilShreyas/ridesharing-uber-lyft-app/blob/master/.github/workflows/Build.yml)

LMK if it looks good to you. See below pictures.

- ***GitHub Actions - Build:***
![1](https://user-images.githubusercontent.com/19620536/77619110-860f1b00-6f5d-11ea-8f1d-5968eed443fe.PNG)

- ***Generated Artifact (APK) on trigger:***
![2](https://user-images.githubusercontent.com/19620536/77619116-88717500-6f5d-11ea-84b3-59471df33bda.PNG)

**Comment by amitshekhariitbhu** [comment]
Great. We will set up everything. Please wait for some time. Sure, we will connect on this.

**Comment by PatilShreyas** [comment]
Sure!

**Comment by amitshekhariitbhu** [comment]
Closing this issue, as we need the key which every user will be getting from the Google Developer Console and keeping it at local only. Later if we plan something, we will update here.
