### ISSUE TITLE
Is it possible to use an api other than google

### ISSUE THREAD

**Issue by ugintl** [MindorksOpenSource/ridesharing-uber-lyft-app#5]
I want to use an api other than google. How to do it?

**Comment by amitshekhariitbhu** [comment]
Currently, the simulator depends on Google APIs

**Comment by kirantpatil** [comment]
Support for Openstreetmap is on the roadmap ?

We need alternative to Google which is Freesoftware in nature.

**Comment by ABcDexter** [comment]
MapMyIndia API is there but it has so many unresolved errors.

**Comment by AdityaV025** [comment]
Use [MapBox](https://docs.mapbox.com/android/maps/guides/)

**Comment by igensis** [comment]
@AdityaV025 Can you tell us how to reply Google with mapbox please

**Comment by gensisco** [comment]
@AdityaV025 Can you tell us how to replace Google with mapbox or OSM please

**Comment by AdityaV025** [comment]
> @AdityaV025 Can you tell us how to reply Google with mapbox or OSM please

I would recommend you to try their [examples ](https://docs.mapbox.com/android/maps/examples/), their documentation is pretty good, try to build an empty app with just the MapBox API, and start implementing different features.

**Comment by mwshubham** [comment]
@igensis Check out my old blog on OSM. Hope this helps a little
https://medium.com/mindorks/have-you-heard-about-open-street-map-d6c51dc00bea

**Comment by Bredan101** [comment]
Hello,
Kindly can you assist me on how to run the source code. Kindly
