### ISSUE TITLE
place and direction api

### ISSUE THREAD

**Issue by noweshed-akram** [MindorksOpenSource/ridesharing-uber-lyft-app#6]
where do I add place and direction API?
I can't search for places, it pops up and disappears when I type for a place.
I have added map API under local properties. is it in the same file with a different string name?

**Comment by bhan-AGL** [comment]
You cannot search for places because You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started

**Comment by CristianFernandoRomero1** [comment]
for people who have trouble adding the API. check out this official link, it worked for me https://blog.mindorks.com/using-local-properties-file-to-avoid-api-keys-check-in-into-version-control-system

add this line in your local.properties file `apiKey = "your_API_key";`
